<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Project</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;500&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="style.css" type='text/css'>

</head>

<body>
    <div class="navbar">
        <ul>
            <li>
                <a href="">
                    <img src="Assets/Techne logo.png" class="logo" id="scroll-top">
                </a>
            </li>
            <li>
                <a href="#">
                    Techne
                </a>
            </li>
        </ul>
    </div>
    <section class="shine-jil" id="shine-jil">
        <div class="heading-text">
            Shine jil projects
        </div>
        <div class="container">
            <div class="project santa-fight">
                
                </div>
                <div class="main-text santa-fight-text">Lorem ipsum dolor sit amet consectetur adipisicing elit.
                    Consequuntur, adipisci. Cum officiis rem voluptatum
                    impedit dicta, est necessitatibus distinctio nisi saepe debitis id aliquam temporibus,
                    incidunt
                    nemo
                    autem
                    voluptate, aspernatur unde quae non!</div>
            </div>

            <div class="project christmas-tree">
               
                </div>
                <div class="main-text christmas-tree-text">Lorem ipsum dolor sit amet consectetur adipisicing
                    elit.
                    Consequuntur, adipisci. Cum officiis rem voluptatum
                    impedit dicta, est necessitatibus distinctio nisi saepe debitis id aliquam temporibus,
                    incidunt
                    nemo
                    autem
                    voluptate, aspernatur unde quae non!</div>
            </div>

            <div class="project quiz-game">
               
                </div>
                <div class="main-text quiz-game-text">Lorem ipsum dolor sit amet consectetur adipisicing elit.
                    Consequuntur, adipisci. Cum officiis rem voluptatum
                    impedit dicta, est necessitatibus distinctio nisi saepe debitis id aliquam temporibus,
                    incidunt
                    nemo
                    autem
                    voluptate, aspernatur unde quae non!</div>
            </div>

            <div class="project firework">
               
                </div>
                <div class="main-text firework-text">Lorem ipsum dolor sit amet consectetur adipisicing elit.
                    Consequuntur, adipisci. Cum officiis rem voluptatum
                    impedit dicta, est necessitatibus distinctio nisi saepe debitis id aliquam temporibus,
                    incidunt
                    nemo
                    autem
                    voluptate, aspernatur unde quae non!</div>
            </div>

            <div class="project random-number">
               
                </div>
                <div class="main-text random-number-text">Lorem ipsum dolor sit amet consectetur adipisicing
                    elit.
                    Consequuntur, adipisci. Cum officiis rem voluptatum
                    impedit dicta, est necessitatibus distinctio nisi saepe debitis id aliquam temporibus,
                    incidunt
                    nemo
                    autem
                    voluptate, aspernatur unde quae non!</div>
            </div>
        </div>

    </section>

    <span class="line"></span>

    <section class="shine-jil">
        <div class="heading-text">
            Snail game project
        </div>
        <div class="project santa-fight">
            
            <div class="main-text santa-fight-text">Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Consequuntur, adipisci. Cum officiis rem voluptatum
                impedit dicta, est necessitatibus distinctio nisi saepe debitis id aliquam temporibus, incidunt nemo
                autem
                voluptates, aspernatur unde quae non!
            </div>

        </div>
        <div class="project christmas-tree">
           
            <div class="main-text christmas-tree-text">Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Consequuntur, adipisci. Cum officiis rem voluptatum
                impedit dicta, est necessitatibus distinctio nisi saepe debitis id aliquam temporibus, incidunt nemo
                autem
                voluptates, aspernatur unde quae non!
            </div>
        </div>
        <div class="project quiz-game">
           
            <div class="main-text quiz-game-text">Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Consequuntur, adipisci. Cum officiis rem voluptatum
                impedit dicta, est necessitatibus distinctio nisi saepe debitis id aliquam temporibus, incidunt nemo
                autem
                voluptates, aspernatur unde quae non!
            </div>
        </div>

    </section>
</body>

</html>